FROM node:18-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    curl \
    unzip \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* awscliv2.zip aws

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

CMD ["node", "VideoTranscoder.js"]
